title: My first blog
author: Nathan Laing
email: ktmlaing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog made using GitHub Pages for the GitHub Learning Labs course

# social links
twitter_username: Nathan__Laing
github_username:  Charybdiss

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
